# Generated by Django 4.2.16 on 2024-10-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0003_alter_supplement_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplement',
            old_name='benefits',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='side_effects',
        ),
    ]
