# Generated by Django 4.2.16 on 2024-09-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='lang',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=2),
            preserve_default=False,
        ),
    ]
