# Generated by Django 4.2.16 on 2024-10-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medication_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='side_effects',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='uses',
        ),
    ]
